CREATE DATABASE IF NOT EXISTS smartbuy_db;
USE smartbuy_db;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('user', 'admin') DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    category VARCHAR(50),
    price DECIMAL(10, 2) NOT NULL,
    stock INT NOT NULL DEFAULT 0,
    image_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    product_id INT,
    quantity INT DEFAULT 1,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    customer_name VARCHAR(100),
    total_amount DECIMAL(10, 2) NOT NULL,
    status ENUM('Pending', 'Processing', 'Shipped', 'Delivered') DEFAULT 'Pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT,
    price DECIMAL(10, 2),
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Insert sample admin account (Password: 'admin123' - generated by werkzeug.security)
INSERT INTO admin (username, password) VALUES ('admin', 'scrypt:32768:8:1$g7MgXUt3LoXMVrMJ$280e6db82aa3c972b2d1993708055ea4fb13d94207afb354ee70bc8d762bcd418feaf3cc030a6944986e448930d466bb320296cd7f62b89b87b08c6748099660')
ON DUPLICATE KEY UPDATE username='admin';

-- Insert sample products
INSERT INTO products (name, description, category, price, stock, image_url) VALUES
('Classic White T-Shirt', 'Premium cotton classic white t-shirt for men.', 'Men', 19.99, 100, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&q=80'),
('Women Floral Dress', 'Beautiful summer floral dress for women.', 'Women', 45.99, 50, 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500&q=80'),
('Kids Denim Jacket', 'Stylish blue denim jacket for kids.', 'Kids', 35.50, 30, 'https://images.unsplash.com/photo-1519238396598-a6b12a870ff5?w=500&q=80'),
('Running Shoes', 'Lightweight comfortable running shoes.', 'Shoes', 59.99, 80, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80'),
('Leather Wallet', 'Genuine leather brown wallet.', 'Accessories', 25.00, 40, 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=500&q=80'),
('Men Black Suit', 'Elegant slim fit black suit.', 'Men', 120.00, 20, 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500&q=80');
select *from users;
show  tables;

